import type { Metadata } from "next"
import { Inter, DM_Sans } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })
const dmSans = DM_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${dmSans.className}`}>
        <main className="lg:w-2/5 md:w-2/3 sm:w-4/5 w-full mx-auto flex min-h-screen flex-col items-center gap-4 p-4">
          {children}
        </main>
      </body>
    </html>
  )
}
